import { Thread, Category, Ad } from './types';

export const CATEGORIES: Category[] = [
  { id: '1', name: 'Politics', slug: 'politics' },
  { id: '2', name: 'Crime', slug: 'crime' },
  { id: '3', name: 'Romance', slug: 'romance' },
  { id: '4', name: 'Jobs/Vacancies', slug: 'jobs' },
  { id: '5', name: 'Career', slug: 'career' },
  { id: '6', name: 'Business', slug: 'business' },
  { id: '7', name: 'Investment', slug: 'investment' },
  { id: '8', name: 'NYSC', slug: 'nysc' },
  { id: '9', name: 'Education', slug: 'education' },
  { id: '10', name: 'Autos', slug: 'autos' },
  { id: '11', name: 'Car Talk', slug: 'car-talk' },
  { id: '12', name: 'Properties', slug: 'properties' },
  { id: '13', name: 'Health', slug: 'health' },
  { id: '14', name: 'Travel', slug: 'travel' },
  { id: '15', name: 'Family', slug: 'family' },
  { id: '16', name: 'Culture', slug: 'culture' },
  { id: '17', name: 'Religion', slug: 'religion' },
  { id: '18', name: 'Food', slug: 'food' },
  { id: '19', name: 'Diaries', slug: 'diaries' },
  { id: '20', name: 'Nairaland Ads', slug: 'ads' },
  { id: '21', name: 'Pets', slug: 'pets' },
  { id: '22', name: 'Agriculture', slug: 'agriculture' },
  { id: '23', name: 'Entertainment', slug: 'entertainment' },
  { id: '24', name: 'Jokes', slug: 'jokes' },
  { id: '25', name: 'TV/Movies', slug: 'tv-movies' },
  { id: '26', name: 'Music/Radio', slug: 'music-radio' },
  { id: '27', name: 'Celebs', slug: 'celebs' },
  { id: '28', name: 'Fashion', slug: 'fashion' },
  { id: '29', name: 'Events', slug: 'events' },
  { id: '30', name: 'Sports', slug: 'sports' },
  { id: '31', name: 'Gaming', slug: 'gaming' },
  { id: '32', name: 'Forum Games', slug: 'forum-games' },
  { id: '33', name: 'Literature', slug: 'literature' },
  { id: '34', name: 'Webmasters', slug: 'webmasters' },
  { id: '35', name: 'Programming', slug: 'programming' },
  { id: '36', name: 'Technology', slug: 'technology' },
  { id: '37', name: 'Phones', slug: 'phones' },
  { id: '38', name: 'Art', slug: 'art' },
];

export const PULSE_THREADS: Thread[] = [
  {
    id: 'p1',
    title: "Tinubu Delivers Keynote Address At 2026 Sustainability Week In Abu Dhabi",
    category: "Politics",
    author: "NairalandNews",
    replies: 452,
    views: 12000,
    timestamp: "2 hrs ago",
    preview: "President Bola Tinubu has arrived in Abu Dhabi for the sustainability week...",
    isTrending: true,
    hasMedia: true
  },
  {
    id: 'p5',
    title: "My Wife Slapped Me In Front Of My Mother-In-Law, I Am Done",
    category: "Romance",
    author: "BrokenHeart01",
    replies: 2304,
    views: 156000,
    timestamp: "45 mins ago",
    preview: "I never thought I would be bringing my marital issues to a public forum, but I am at my wits end. Yesterday was the final straw...",
    isTrending: true,
    hasMedia: false
  },
  {
    id: 'p2',
    title: "AFCON 2025: Countries With Highest Foreign Born Players",
    category: "Sports",
    author: "GoalDigger",
    replies: 890,
    views: 35000,
    timestamp: "4 hrs ago",
    preview: "A statistical breakdown of squad compositions for the upcoming AFCON tournament.",
    isTrending: true,
    hasMedia: true
  },
  {
    id: 'p3',
    title: "US AFRICOM Meets Marwa, Pledges More Support To NDLEA",
    category: "Crime",
    author: "SecurityWatch",
    replies: 120,
    views: 5400,
    timestamp: "1 hr ago",
    preview: "High level meetings held today between US officials and the NDLEA chairman.",
    isTrending: false,
    hasMedia: true
  },
  {
    id: 'p4',
    title: "Native Doctor Who Promised Mall AFCON Victory After Collecting €33,500 Arrested",
    category: "Crime",
    author: "NewsBot",
    replies: 1240,
    views: 89000,
    timestamp: "30 mins ago",
    preview: "Police have apprehended a self-acclaimed spiritualist for alleged fraud.",
    isTrending: true,
    hasMedia: false
  },
  {
    id: 'p6',
    title: "Cooking Gas Prices Drop To N900/kg In Lagos And Abuja",
    category: "Economy",
    author: "MarketWatch",
    replies: 340,
    views: 18000,
    timestamp: "1 hr ago",
    preview: "Consumers breathe a sigh of relief as LPG prices finally see a downward trend...",
    isTrending: true
  },
  {
    id: 'p7',
    title: "VeryDarkMan Release From Police Custody Sparks Jubilation",
    category: "Celebrities",
    author: "GistMaster",
    replies: 1205,
    views: 95000,
    timestamp: "3 hrs ago",
    preview: "The controversial activist was welcomed by hundreds of supporters...",
    isTrending: true
  },
  {
    id: 'p8',
    title: "Dangote Refinery Begins Petrol Loading Sunday",
    category: "Business",
    author: "EnergyNews",
    replies: 890,
    views: 45000,
    timestamp: "5 hrs ago",
    preview: "Marketers are preparing trucks as the refinery sets to roll out PMS...",
    isTrending: true
  },
  {
    id: 'p9',
    title: "Who Is The Best Governor In Nigeria Currently?",
    category: "Politics",
    author: "PoliticZone",
    replies: 2300,
    views: 67000,
    timestamp: "6 hrs ago",
    preview: "Let's discuss objective achievements. Drop your state and governor...",
    isTrending: true
  }
];

export const MAIN_FEED_THREADS: Thread[] = [
  {
    id: '1',
    title: "If You Can't Handle This, Don't Date A Single Mom",
    category: "Romance",
    author: "LoveDoctor",
    replies: 342,
    views: 15000,
    timestamp: "15 mins ago",
    preview: "Dating a single mother comes with specific responsibilities that many men overlook...",
    isTrending: true
  },
  {
    id: '2',
    title: "Kwankwaso Makes U-Turn, Endorses Governor Yusuf, NNPP Members' Defection To APC",
    category: "Politics",
    author: "PoliticalAnalyst",
    replies: 156,
    views: 4200,
    timestamp: "1 hour ago",
    preview: "The political landscape in Kano shifts again as Kwankwaso clarifies his stance.",
    isBreaking: true
  },
  {
    id: '3',
    title: "Makinde, Bala Will Soon Defect To ADC - Fayose (Video)",
    category: "Politics",
    author: "WhistleBlower",
    replies: 89,
    views: 3100,
    timestamp: "2 hours ago",
    preview: "Former Governor Fayose claims sitting governors are planning a strategic move.",
    hasMedia: true
  },
  {
    id: '4',
    title: "\"I Am Dying\" – Actress Halima Abubakar Breaks Down In Tears, Cries Out For Help",
    category: "Celebrities",
    author: "NollyGist",
    replies: 567,
    views: 45000,
    timestamp: "3 hours ago",
    preview: "The veteran actress took to Instagram live to share her health struggles.",
    isTrending: true
  },
  {
    id: '5',
    title: "US Labels Muslim Brotherhood In Egypt, Lebanon, Jordan As Terrorist Organisations",
    category: "Foreign Affairs",
    author: "GlobalWatch",
    replies: 230,
    views: 8900,
    timestamp: "4 hours ago",
    preview: "A major foreign policy shift announced by the State Department today.",
  },
  {
    id: '6',
    title: "Trump To Iranian Protesters: Keep Protesting, Help Is On Its Way",
    category: "Foreign Affairs",
    author: "USPolitics",
    replies: 112,
    views: 3400,
    timestamp: "5 hours ago",
    preview: "Former President Trump sends a message of solidarity to protesters in Tehran.",
  },
  {
    id: '7',
    title: "See The New Nigeria Army Depot In Osogbo",
    category: "Defense",
    author: "MilitaryZone",
    replies: 45,
    views: 1200,
    timestamp: "6 hours ago",
    preview: "Photos emerging from the newly commissioned Army Depot show state of the art facilities.",
    hasMedia: true
  },
  {
    id: '8',
    title: "How Do You Feel Eating An Animal That Has Human Features?",
    category: "Food",
    author: "CuriousMind",
    replies: 890,
    views: 22000,
    timestamp: "7 hours ago",
    preview: "A philosophical debate on the ethics of consuming primates and other bushmeat.",
  },
  {
    id: '9',
    title: "APC Hunts Down Students, Negotiates With Bandits – Atiku On Ekpoma Protest",
    category: "Politics",
    author: "OppositionVoice",
    replies: 334,
    views: 11000,
    timestamp: "8 hours ago",
    preview: "Atiku Abubakar has criticized the ruling party's handling of recent student protests.",
  },
  {
    id: '10',
    title: "Otti's Wife Urges Inmates To Embrace Positive Transformation",
    category: "Crime",
    author: "AbiaNews",
    replies: 23,
    views: 800,
    timestamp: "9 hours ago",
    preview: "During a prison visit, the First Lady of Abia State encouraged rehabilitation.",
  },
  {
    id: '11',
    title: "I Need Husband - Actres Princess Dami Begs Popular Men Of God (Video)",
    category: "Romance",
    author: "GistLover",
    replies: 678,
    views: 56000,
    timestamp: "10 hours ago",
    preview: "The actress has openly requested prayers for a life partner.",
    hasMedia: true
  },
  {
    id: '12',
    title: "CBN Governor Sanusi Clears Air On Currency Redesign",
    category: "Economy",
    author: "BizInsider",
    replies: 999,
    views: 102000,
    timestamp: "11 hours ago",
    preview: "The CBN Governor has issued a statement clarifying rumors about new notes.",
  },
  {
    id: '13',
    title: "My Landlord Increased Rent By 300%, Is This Legal?",
    category: "Properties",
    author: "Tenant001",
    replies: 156,
    views: 8000,
    timestamp: "12 hours ago",
    preview: "I live in Lekki Phase 1 and my landlord just served me a notice.",
  },
  {
    id: '14',
    title: "Super Eagles Coach: We Are Ready For The World Cup",
    category: "Sports",
    author: "SportyNaija",
    replies: 78,
    views: 5000,
    timestamp: "13 hours ago",
    preview: "Press conference highlights from the Super Eagles camp.",
    hasMedia: true
  },
  {
    id: '15',
    title: "Japa: UK Government Announces New Visa Rules For Dependents",
    category: "Travel",
    author: "TravelGuide",
    replies: 2500,
    views: 300000,
    timestamp: "1 day ago",
    preview: "Important update for Nigerians planning to relocate to the UK.",
    isTrending: true
  }
];

export const NEW_THREADS: Thread[] = [
  {
    id: 'n1',
    title: "Just Saw A Strange Bird In My Compound (Photos)",
    category: "Pets",
    author: "NatureLover",
    replies: 2,
    views: 45,
    timestamp: "Just now",
    preview: "Can anyone identify this species? It looks very colorful.",
    hasMedia: true
  },
  {
    id: 'n2',
    title: "Looking For Original iPhone 15 Pro Max Charger",
    category: "Phones",
    author: "GadgetFreak",
    replies: 0,
    views: 12,
    timestamp: "2 mins ago",
    preview: "Please I need a vendor in Ikeja. Must be original.",
  },
  {
    id: 'n3',
    title: "Manchester United vs Liverpool: Match Day Thread",
    category: "Sports",
    author: "RedDevil",
    replies: 15,
    views: 300,
    timestamp: "5 mins ago",
    preview: "Lineups are out! Let's discuss the game.",
  },
  {
    id: 'n4',
    title: "Python or JavaScript for a beginner in 2025?",
    category: "Programming",
    author: "CodeNewbie",
    replies: 4,
    views: 89,
    timestamp: "12 mins ago",
    preview: "I want to start my tech journey but I am confused.",
  },
  {
    id: 'n5',
    title: "Help! My Car Overheats Whenever I Use AC",
    category: "Car Talk",
    author: "DriverX",
    replies: 8,
    views: 150,
    timestamp: "20 mins ago",
    preview: "It's a Toyota Camry 2018 model. Mechanics are confusing me.",
  },
  {
    id: 'n6',
    title: "Best Shawarma Spot In Abuja?",
    category: "Food",
    author: "FoodieAbj",
    replies: 22,
    views: 400,
    timestamp: "35 mins ago",
    preview: "Recommendations needed for Wuse 2 area.",
  },
  {
    id: 'n7',
    title: "Urgent: Nanny Needed In Lekki Phase 1",
    category: "Jobs",
    author: "LekkiMom",
    replies: 1,
    views: 60,
    timestamp: "45 mins ago",
    preview: "Live-in nanny needed. Must be experienced.",
  },
  {
    id: 'n8',
    title: "Review of the New Tecno Phantom V Fold 3",
    category: "Technology",
    author: "TechReviewer",
    replies: 34,
    views: 1200,
    timestamp: "50 mins ago",
    preview: "Is it worth the price tag? Here is my honest review.",
    hasMedia: true
  },
  {
    id: 'n9',
    title: "Prayer Points For The Week",
    category: "Religion",
    author: "PrayerWarrior",
    replies: 5,
    views: 90,
    timestamp: "55 mins ago",
    preview: "Let us commit the new week into God's hands.",
  },
  {
    id: 'n10',
    title: "Wedding Guest Aso-Ebi Styles 2025",
    category: "Fashion",
    author: "StyleChic",
    replies: 12,
    views: 600,
    timestamp: "1 hour ago",
    preview: "Check out these trending styles for your next owambe.",
    hasMedia: true
  }
];

export const FOLLOWING_THREADS: Thread[] = [
  {
    id: 'f1',
    title: "My Investment Portfolio Update - Q1 2025",
    category: "Investment",
    author: "SmartMoney",
    replies: 45,
    views: 2300,
    timestamp: "3 hours ago",
    preview: "Sharing my gains and losses from the stock market and crypto.",
  },
  {
    id: 'f2',
    title: "New React Native Architecture Explained",
    category: "Programming",
    author: "DevGuru",
    replies: 12,
    views: 800,
    timestamp: "5 hours ago",
    preview: "A deep dive into the new fabrication architecture.",
  },
  {
    id: 'f3',
    title: "Exclusive: Behind The Scenes At The AMVCA",
    category: "Celebs",
    author: "EntertainmentWeekly",
    replies: 156,
    views: 15000,
    timestamp: "8 hours ago",
    preview: "We got exclusive access to the red carpet.",
    hasMedia: true
  },
  {
    id: 'f4',
    title: "Why I Left Canada And Returned To Nigeria",
    category: "Travel",
    author: "ReturneeDiary",
    replies: 890,
    views: 45000,
    timestamp: "1 day ago",
    preview: "It wasn't an easy decision, but here is my story.",
  },
  {
    id: 'f5',
    title: "Learn How To Bake Cake From Scratch (Free Class)",
    category: "Food",
    author: "BakerExtraordinaire",
    replies: 230,
    views: 5600,
    timestamp: "1 day ago",
    preview: "Join my free telegram class starting tomorrow.",
  },
  {
    id: 'f6',
    title: "Analysis of the 2025 Budget",
    category: "Politics",
    author: "PolicyAnalyst",
    replies: 67,
    views: 3400,
    timestamp: "2 days ago",
    preview: "Breaking down the numbers for the common man.",
  }
];

export const ADS: Ad[] = [
  {
    id: 'ad1',
    company: 'Paripesa',
    tagline: 'Bet on AFCON with Yaya Toure. Instant payouts.',
    ctaText: 'Bet Now'
  },
  {
    id: 'ad2',
    company: 'Moniepoint',
    tagline: 'Reliable banking for your business. Get your POS today.',
    ctaText: 'Get Started'
  },
  {
    id: 'ad3',
    company: 'Infinix',
    tagline: 'The new Note 40 Pro is here. Charge 100% in 15 mins.',
    ctaText: 'Buy Now'
  }
];
